language: php

php:
  - 5.6
  - 7.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - "mkdir -p ~/.composer"
  - openssl aes-256-cbc -K $encrypted_c7ba8b8ecc4c_key -iv $encrypted_c7ba8b8ecc4c_iv -in .travis.composer.config.json.enc -out ~/.composer/config.json -d

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - composer require satooshi/php-coveralls
  - travis_retry vendor/bin/coveralls
